#!/bin/bash

frames=(
"
      (•_•)
     <)   )╯
      /   \\
"
"
      (•_•)
     <)   )>
      /   \\
"
"
      (•_•)
     ╰(   (>
      /   \\
"
"
      (•_•)
     <)   )╯
      /   \\
"
)

clear

max_spaces=30

while true; do
  for (( i=0; i<=$max_spaces; i++ )); do
    for frame in "${frames[@]}"; do
      clear
      spaces=$(printf "%${i}s" "") 
      while IFS= read -r line; do
        echo "${spaces}${line}"
      done <<< "$frame"
      sleep 0.1
    done
  done
done